// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import JobTriggerController from "./job_trigger_controller";
application.register("job-trigger", JobTriggerController);

import PasswordStrengthController from "./password_strength_controller";
application.register("password-strength", PasswordStrengthController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);

import DropdownController from "./dropdown_controller";
application.register("dropdown", DropdownController);

import SidebarMenuController from "./sidebar_menu_controller";
application.register("sidebar-menu", SidebarMenuController);

import TogglePasswordVisibilityController from "./toggle_password_visibility";
application.register(
  "toggle-password-visibility",
  TogglePasswordVisibilityController,
);

import CollapsibleController from "./collapsible_controller";
application.register("collapsible", CollapsibleController);

import VideoSelectionController from "./video_selection_controller";
application.register("video-selection", VideoSelectionController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);
